import Navbar from "@/components/navbar/Navbar"
import "../styles/globals.scss"
import Footer from "@/components/footer/Footer"
export const metadata = {
  title: 'webease',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
        </body>
    </html>
  )
}
